@startjson
{
  "tenantId": "It is the keycloak id of the logged in user.",
  "purpose":"Short description of usage",
  "targetIdentities":["List of UUIDs <or>", "Wildcard * <or>", "List of Group Names"],
  "expiration": "# of seconds to expiration",
  "notBefore": "# of seconds to be active",
  "originDomains": ["List of origin domains as http/https urls"],
  "scopes": ["upp:anchor","upp:verify","thing:create"]
}
@endjson
