@startjson
{
  "iss": "https://token.dev.ubirch.com",
  "sub": "tenant id / user id",
  "aud": [
    "https://verify.dev.ubirch.com",
    "https://niomon.dev.ubirch.com",
    "https://api.console.dev.ubirch.com"
    ],
  "exp": 7924869463,
  "iat": 1613479063,
  "jti": "407f29ab-ac74-42c7-81e9-107a53f3de36",
  "pur": "King Dude - Concert",
  "tid": ["List of UUIDs <or>", "List with single Wildcard * <or>"],
  "tgp": ["List of Group UUIDs <or>", "List of Group Names"],
  "ord": [
    "http://verification.dev.ubirch.com"
  ],
  "scp": [
     "upp:anchor",
     "upp:verify",
     "thing:create",
     "thing:getinfo",
     "thing:bootstrap",
     "user:getinfo"
  ]
}
@endjson
