@startuml
actor client #red
box "Token Device Creation Usage" #EDEAE0
client->"Thing API": sends DeviceCreationRequest(identityId, token(thing:create), device_info)
"Thing API"->"Thing API": "Token Service Light SDK" handles validation
"Thing API"->"Token Service": asks for Validation if claim types require it.
"Token Service"->"Thing API": asks for required info if needed
"Thing API"->"Token Service": required info is returned
"Token Service"->"Token Service": Validation is made
"Token Service"->"Thing API": Response is returned
"Thing API"->"Thing API": Claims verification is checked
"Thing API"->client: Device Creation Response is returned
end box
@enduml
